import { integer, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id: integer("id").primaryKey({ autoIncrement: true }), username: text("username").notNull(), displayName: text("display_name").notNull(), passwordHash: text("password_hash").notNull(), passwordSalt: text("password_salt").notNull(), avatarUrl: text("avatar_url"), role: text("role", { enum: ["Administrator", "Projektleiter", "Mitglied", "Gast"] }).notNull().default("Mitglied"), status: text("status", { enum: ["Aktiv", "Deaktiviert"] }).notNull().default("Aktiv"), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), lastLoginAt: integer("last_login_at", { mode: "timestamp" }) }, t => [uniqueIndex("idx_users_username").on(t.username), index("idx_users_status").on(t.status)]);
export const sessions = sqliteTable("sessions", { id: text("id").primaryKey(), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, t => [index("idx_sessions_user_id").on(t.userId), index("idx_sessions_expires_at").on(t.expiresAt)]);
export const projects = sqliteTable("projects", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), description: text("description").notNull().default(""), status: text("status", { enum: ["Geplant", "Aktiv", "Pausiert", "Abgeschlossen", "Archiviert"] }).notNull().default("Aktiv"), startDate: text("start_date").notNull(), endDate: text("end_date"), leadId: integer("lead_id").notNull().references(() => users.id), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, t => [index("idx_projects_status").on(t.status), index("idx_projects_lead_id").on(t.leadId)]);
export const projectMembers = sqliteTable("project_members", { projectId: integer("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), userId: integer("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), projectRole: text("project_role").notNull().default("Mitglied") }, t => [uniqueIndex("idx_project_members_pair").on(t.projectId, t.userId), index("idx_project_members_user_id").on(t.userId)]);
export const tasks = sqliteTable("tasks", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: integer("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), title: text("title").notNull(), description: text("description").notNull().default(""), status: text("status", { enum: ["Offen", "In Bearbeitung", "Blockiert", "In Prüfung", "Erledigt"] }).notNull().default("Offen"), priority: text("priority", { enum: ["Niedrig", "Normal", "Hoch", "Kritisch"] }).notNull().default("Normal"), assigneeId: integer("assignee_id").references(() => users.id), creatorId: integer("creator_id").notNull().references(() => users.id), startDate: text("start_date"), dueDate: text("due_date"), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() }, t => [index("idx_tasks_project_status").on(t.projectId, t.status), index("idx_tasks_assignee_status").on(t.assigneeId, t.status), index("idx_tasks_due_date").on(t.dueDate)]);
export const comments = sqliteTable("comments", { id: integer("id").primaryKey({ autoIncrement: true }), taskId: integer("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }), authorId: integer("author_id").notNull().references(() => users.id), content: text("content").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() }, t => [index("idx_comments_task_created").on(t.taskId, t.createdAt)]);
export const documentFolders = sqliteTable("document_folders", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), projectId: integer("project_id").references(() => projects.id, { onDelete: "cascade" }), parentId: integer("parent_id"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, t => [index("idx_document_folders_parent").on(t.parentId), index("idx_document_folders_project").on(t.projectId)]);
export const documents = sqliteTable("documents", { id: integer("id").primaryKey({ autoIncrement: true }), folderId: integer("folder_id").references(() => documentFolders.id, { onDelete: "set null" }), projectId: integer("project_id").references(() => projects.id, { onDelete: "cascade" }), title: text("title").notNull(), content: text("content").notNull().default(""), authorId: integer("author_id").notNull().references(() => users.id), createdAt: integer("created_at", { mode: "timestamp" }).notNull(), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull() }, t => [index("idx_documents_folder").on(t.folderId), index("idx_documents_project").on(t.projectId), index("idx_documents_updated").on(t.updatedAt)]);
export const calendarEvents = sqliteTable("calendar_events", { id: integer("id").primaryKey({ autoIncrement: true }), projectId: integer("project_id").references(() => projects.id, { onDelete: "cascade" }), title: text("title").notNull(), type: text("type", { enum: ["Termin", "Meilenstein"] }).notNull().default("Termin"), startsAt: integer("starts_at", { mode: "timestamp" }).notNull(), endsAt: integer("ends_at", { mode: "timestamp" }), createdBy: integer("created_by").notNull().references(() => users.id) }, t => [index("idx_calendar_events_start").on(t.startsAt), index("idx_calendar_events_project").on(t.projectId)]);
export const activities = sqliteTable("activities", { id: integer("id").primaryKey({ autoIncrement: true }), actorId: integer("actor_id").notNull().references(() => users.id), projectId: integer("project_id").references(() => projects.id, { onDelete: "cascade" }), entityType: text("entity_type").notNull(), entityId: integer("entity_id"), action: text("action").notNull(), details: text("details"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, t => [index("idx_activities_project_created").on(t.projectId, t.createdAt), index("idx_activities_actor_created").on(t.actorId, t.createdAt)]);
